name: Daily Commit Workflow

on:
  schedule:
    - cron: "30 6 * * *"  # runs daily at 06:30 UTC
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add dummy update by 23f3003748@ds.study.iitm.ac.in
        run: |
          echo "Last run at $(date -u)" >> last-run.log

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add last-run.log
          git commit -m "Daily update - $(date -u) [skip ci]" || echo "No changes to commit"
          git push

