name: Daily Commit

on:
  schedule:
    - cron: "5 3 * * *"  # Runs daily at 03:05 UTC
  workflow_dispatch:    # Allows manual run from Actions tab

jobs:
  update-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: 23f3003748@ds.study.iitm.ac.in - Make a daily commit
        run: |
          echo "Daily update: $(date)" >> daily-log.txt
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add daily-log.txt
          git commit -m "Daily commit [skip ci]" || echo "Nothing to commit"
          git push
